language: go

sudo: false

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - tip
  - master

before_install:
  - go get github.com/WindomZ/testify/assert
  - go get github.com/docopt/docopt-go
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -ignore="*/*example.go" -service=travis-ci
  - go test -v ./...
